### ISSUE TITLE
error when test setr with aug-test

### ISSUE THREAD

**Issue by ydhongHIT** [open-mmlab/mmsegmentation#738] opened 2021-07-28 12:23 UTC
If the short side of image is smaller than crop_size, the input size isn't in line with crop_size. But setr models only accept the input of fixed size. So how can I get the multi-scale test results of setr?

**Comment by ydhongHIT** [comment] 2021-07-28 12:30
I find the offcial implement of setr overwrite this class. https://github.com/open-mmlab/mmsegmentation/blob/fa1554f1aaea9a2c58249b06e1ea48420091464d/mmseg/datasets/pipelines/transforms.py#L10 I guess how do you get the multi-scale test results using current repo.

**Comment by sennnnn** [comment] 2021-07-28 12:54
@ydhongHIT 
Sorry, we will try to reproduce this bug and try to fix it recently. 🙏🙏

**Comment by ydhongHIT** [comment] 2021-07-28 12:59
> @ydhongHIT
> Sorry, we will try to reproduce this bug and try to fix it recently. 🙏🙏

Thanks for instant reply. I notice that you report the multi-scale test results of setr in the model zoo. Do you mean that the mutli-scale results are produced by your local code?

**Comment by Junjun2016** [comment] 2021-07-29 02:06
Hi @ydhongHIT 
Could you please provide the log, config, and command?
It is more convenient for us to debug.

**Comment by ydhongHIT** [comment] 2021-07-29 02:11
> Hi @ydhongHIT
> Could you please provide the log, config, and command?
> It is more convenient for us to debug.

Just test the pretrained setr models with 'aug-test'.

**Comment by ydhongHIT** [comment] 2021-07-29 02:37
Or multi-scale test any model which needs input of fixed size.

**Comment by Junjun2016** [comment] 2021-07-29 09:26
> > Hi @ydhongHIT
> > Could you please provide the log, config, and command?
> > It is more convenient for us to debug.
> 
> Just test the pretrained setr models with 'aug-test'. Or multi-scale test any model which needs input of fixed size.

We tested aug-test with the latest version. it worked.
Since we pad the input to be multiple of patch size.
https://github.com/open-mmlab/mmsegmentation/blob/fa1554f1aaea9a2c58249b06e1ea48420091464d/mmseg/models/utils/embed.py#L83

Could you please check it and provide detailed bug information.

**Comment by sennnnn** [comment] 2021-07-29 16:22
Sorry, the multi-scale test is provided by using resize from [this](https://github.com/fudan-zvg/SETR/blob/23f8fde88182c7965e91c28a0c59d9851af46858/mmseg/datasets/pipelines/transforms.py#L9). But the code may be a little bit dirty, we remove this part of code. We plan to use a more elegant way to solve this problem.

**Comment by ydhongHIT** [comment] 2021-07-30 04:29
> > > Hi @ydhongHIT
> > > Could you please provide the log, config, and command?
> > > It is more convenient for us to debug.
> > 
> > 
> > Just test the pretrained setr models with 'aug-test'. Or multi-scale test any model which needs input of fixed size.
> 
> We tested aug-test with the latest version. it worked.
> Since we pad the input to be multiple of patch size.
> https://github.com/open-mmlab/mmsegmentation/blob/fa1554f1aaea9a2c58249b06e1ea48420091464d/mmseg/models/utils/embed.py#L83
> 
> Could you please check it and provide detailed bug information.

It only ensures that input size is divisible by patch size but can't ensure that input size is fixed such as 768x768 for cityscapes or 512x512 for ADE20K during multi-scale test.

**Comment by ydhongHIT** [comment] 2021-07-30 05:36
> > > Hi @ydhongHIT
> > > Could you please provide the log, config, and command?
> > > It is more convenient for us to debug.
> > 
> > 
> > Just test the pretrained setr models with 'aug-test'. Or multi-scale test any model which needs input of fixed size.
> 
> We tested aug-test with the latest version. it worked.
> Since we pad the input to be multiple of patch size.
> https://github.com/open-mmlab/mmsegmentation/blob/fa1554f1aaea9a2c58249b06e1ea48420091464d/mmseg/models/utils/embed.py#L83
> 
> Could you please check it and provide detailed bug information.

I didn't test with the latest version and add the config of setr manually.

**Comment by Junjun2016** [comment] 2021-07-30 05:54
> > > > Hi @ydhongHIT
> > > > Could you please provide the log, config, and command?
> > > > It is more convenient for us to debug.
> > > 
> > > 
> > > Just test the pretrained setr models with 'aug-test'. Or multi-scale test any model which needs input of fixed size.
> > 
> > 
> > We tested aug-test with the latest version. it worked.
> > Since we pad the input to be multiple of patch size.
> > https://github.com/open-mmlab/mmsegmentation/blob/fa1554f1aaea9a2c58249b06e1ea48420091464d/mmseg/models/utils/embed.py#L83
> > 
> > Could you please check it and provide detailed bug information.
> 
> It only ensures that input size is divisible by patch size but can't ensure that input size is fixed such as 768x768 for cityscapes or 512x512 for ADE20K during multi-scale test.

Sure, it can't ensure that input size is fixed if `min(image size)` < `crop size` which leads to the size of cropped image is smaller than the` crop size`, but it can do inference with `pad_to_patch_size=True`.

**Comment by ydhongHIT** [comment] 2021-07-30 06:00
> > > > > Hi @ydhongHIT
> > > > > Could you please provide the log, config, and command?
> > > > > It is more convenient for us to debug.
> > > > 
> > > > 
> > > > Just test the pretrained setr models with 'aug-test'. Or multi-scale test any model which needs input of fixed size.
> > > 
> > > 
> > > We tested aug-test with the latest version. it worked.
> > > Since we pad the input to be multiple of patch size.
> > > https://github.com/open-mmlab/mmsegmentation/blob/fa1554f1aaea9a2c58249b06e1ea48420091464d/mmseg/models/utils/embed.py#L83
> > > 
> > > Could you please check it and provide detailed bug information.
> > 
> > 
> > It only ensures that input size is divisible by patch size but can't ensure that input size is fixed such as 768x768 for cityscapes or 512x512 for ADE20K during multi-scale test.
> 
> Sure, it can't ensure that input size is fixed if `min(image size)` < `crop size` which leads to the size of cropped image is smaller than the` crop size`, but it can do inference with `pad_to_patch_size=True`.

I think it is different from the original setr implement because they seem to keep the input size fixed. It seems that absolute position encodings are sensitive to input scale, referring to https://arxiv.org/pdf/2102.10882.pdf.

**Comment by Junjun2016** [comment] 2021-07-30 06:22
> > > > > > Hi @ydhongHIT
> > > > > > Could you please provide the log, config, and command?
> > > > > > It is more convenient for us to debug.
> > > > > 
> > > > > 
> > > > > Just test the pretrained setr models with 'aug-test'. Or multi-scale test any model which needs input of fixed size.
> > > > 
> > > > 
> > > > We tested aug-test with the latest version. it worked.
> > > > Since we pad the input to be multiple of patch size.
> > > > https://github.com/open-mmlab/mmsegmentation/blob/fa1554f1aaea9a2c58249b06e1ea48420091464d/mmseg/models/utils/embed.py#L83
> > > > 
> > > > Could you please check it and provide detailed bug information.
> > > 
> > > 
> > > It only ensures that input size is divisible by patch size but can't ensure that input size is fixed such as 768x768 for cityscapes or 512x512 for ADE20K during multi-scale test.
> > 
> > 
> > Sure, it can't ensure that input size is fixed if `min(image size)` < `crop size` which leads to the size of cropped image is smaller than the` crop size`, but it can do inference with `pad_to_patch_size=True`.
> 
> I think it is different from the original setr implement because they seem to keep the input size fixed. It seems that absolute position encodings are sensitive to input scale, referring to https://arxiv.org/pdf/2102.10882.pdf.

Yes, exactly.
We try to re-implement it with the paper's original settings while maintaining consistency with our codebase settings.
Maybe we can provide the results with different settings for multi-scale testing.
What's your opinion?

**Comment by ydhongHIT** [comment] 2021-07-30 14:06
> > > > > > > Hi @ydhongHIT
> > > > > > > Could you please provide the log, config, and command?
> > > > > > > It is more convenient for us to debug.
> > > > > > 
> > > > > > 
> > > > > > Just test the pretrained setr models with 'aug-test'. Or multi-scale test any model which needs input of fixed size.
> > > > > 
> > > > > 
> > > > > We tested aug-test with the latest version. it worked.
> > > > > Since we pad the input to be multiple of patch size.
> > > > > https://github.com/open-mmlab/mmsegmentation/blob/fa1554f1aaea9a2c58249b06e1ea48420091464d/mmseg/models/utils/embed.py#L83
> > > > > 
> > > > > Could you please check it and provide detailed bug information.
> > > > 
> > > > 
> > > > It only ensures that input size is divisible by patch size but can't ensure that input size is fixed such as 768x768 for cityscapes or 512x512 for ADE20K during multi-scale test.
> > > 
> > > 
> > > Sure, it can't ensure that input size is fixed if `min(image size)` < `crop size` which leads to the size of cropped image is smaller than the` crop size`, but it can do inference with `pad_to_patch_size=True`.
> > 
> > 
> > I think it is different from the original setr implement because they seem to keep the input size fixed. It seems that absolute position encodings are sensitive to input scale, referring to https://arxiv.org/pdf/2102.10882.pdf.
> 
> Yes, exactly.
> We try to re-implement it with the paper's original settings while maintaining consistency with our codebase settings.
> Maybe we can provide the results with different settings for multi-scale testing.
> What's your opinion?

Thanks for your reply. I guess which test method is better. I have another question about the image resolution. During training, the input resolution is fixed (i.e. crop_size) for cityscapes and ade20k but pascal_context not. What's the reason for the difference? And what shoud I do to keep the resolution constant.

**Comment by Junjun2016** [comment] 2021-07-30 17:27
> > > > > > > > Hi @ydhongHIT
> > > > > > > > Could you please provide the log, config, and command?
> > > > > > > > It is more convenient for us to debug.
> > > > > > > 
> > > > > > > 
> > > > > > > Just test the pretrained setr models with 'aug-test'. Or multi-scale test any model which needs input of fixed size.
> > > > > > 
> > > > > > 
> > > > > > We tested aug-test with the latest version. it worked.
> > > > > > Since we pad the input to be multiple of patch size.
> > > > > > https://github.com/open-mmlab/mmsegmentation/blob/fa1554f1aaea9a2c58249b06e1ea48420091464d/mmseg/models/utils/embed.py#L83
> > > > > > 
> > > > > > Could you please check it and provide detailed bug information.
> > > > > 
> > > > > 
> > > > > It only ensures that input size is divisible by patch size but can't ensure that input size is fixed such as 768x768 for cityscapes or 512x512 for ADE20K during multi-scale test.
> > > > 
> > > > 
> > > > Sure, it can't ensure that input size is fixed if `min(image size)` < `crop size` which leads to the size of cropped image is smaller than the` crop size`, but it can do inference with `pad_to_patch_size=True`.
> > > 
> > > 
> > > I think it is different from the original setr implement because they seem to keep the input size fixed. It seems that absolute position encodings are sensitive to input scale, referring to https://arxiv.org/pdf/2102.10882.pdf.
> > 
> > 
> > Yes, exactly.
> > We try to re-implement it with the paper's original settings while maintaining consistency with our codebase settings.
> > Maybe we can provide the results with different settings for multi-scale testing.
> > What's your opinion?
> 
> Thanks for your reply. I guess which test method is better. I have another question about the image resolution. During training, the input resolution is fixed (i.e. crop_size) for cityscapes and ade20k but pascal_context not. What's the reason for the difference? And what shoud I do to keep the resolution constant.

We keep the crop size fixed in training.

**Closed** 2021-09-15 09:02 UTC
Labels: bug
