### ISSUE TITLE
Tried to modify the maxpool layer of backbone(resnet-r50-d8),but failed.

### ISSUE THREAD

**Issue by Xiaxia1997** [open-mmlab/mmsegmentation#1116] opened 2021-12-08 08:03 UTC
The network I used is **ICnet_resnet_r50_d8**. I want to change the maxpool layer of backbone for my project. The goal is to change the maxpool's kernel size from 3 to 2 and padding from 1 to 0.
The problem is that I have already changed the maxpool layer in codes, and it worked in log. However, the parameters of maxpool layer didn't changed in onnx.
I changed two places in codes.
1. The old maxpool layer:  **/mmseg/models/backbones/icnet.py line73**
```self.backbone.maxpool = nn.MaxPool2d( kernel_size=3, stride=2, padding=1, ceil_mode=True)```
I modified it to be : ```self.backbone.maxpool = nn.MaxPool2d(kernel_size=2, stride=2, padding=0, ceil_mode=True)```
2. Also, since the backbone I used is resnet-r50-d8, I changed the maxpool in resnet. **/mmseg/models/backbones/resney.py line638**
```self.maxpool = nn.MaxPool2d(kernel_size=2, stride=2, padding=0)```
But the new model got the old parameters as shown below.
![截图](https://user-images.githubusercontent.com/95740788/145170841-daf4a886-7d4d-447a-8853-9b2780d9dff8.PNG)

**So how to change the maxpool layer?** 
System info is shown below
```
sys.platform: linux
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) [GCC 9.4.0]
GPU 0,1,2,3: Tesla V100-SXM2-16GB
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
TorchVision: 0.7.0
OpenCV: 3.4.4
MMCV: 1.3.17
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMSegmentation: 0.19.0+```

**Comment by MengzhangLI** [comment] 2021-12-16 17:28
Hi, sorry for late reply.
 
Do you have related error info?

From your description, I can not tell something wrong in your modification.

If it works well in training and inference and only fails in transferring to onnx, I think it is caused by onnx.

**Closed** 2021-12-31 09:40 UTC
