### ISSUE TITLE
AssertionError: CustomDataset: `cls.CLASSES` or `classes` should be specified when testing

### ISSUE THREAD

**Issue by 2458zhanghehe** [open-mmlab/mmsegmentation#2693] opened 2023-03-05 06:20 UTC
What should I do

**Comment by xiexinch** [comment] 2023-03-06 04:54
Hi @2458zhanghehe, thanks for your error report we appreciate it a lot, please provide more information.

**Checklist**

1. I have searched for related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
A clear and concise description of what the bug is.

**Reproduction**

1. What command or script did you run?

   ```none
   A placeholder for the command.
   ```

2. Did you make any modifications to the code or config? Did you understand what you have modified?

3. What dataset did you use?

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect the necessary environmental information and paste it here.
2. You may add an addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by 2458zhanghehe** [comment] 2023-03-06 04:59
> Hi @2458zhanghehe, thanks for your error report we appreciate it a lot, please provide more information.
> 
> **Checklist**
> 
> 1. I have searched for related issues but cannot get the expected help.
> 2. The bug has not been fixed in the latest version.
> 
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **Reproduction**
> 
> 1. What command or script did you run?
>    ```
>    A placeholder for the command.
>    ```
> 2. Did you make any modifications to the code or config? Did you understand what you have modified?
> 3. What dataset did you use?
> 
> **Environment**
> 
> 1. Please run `python mmseg/utils/collect_env.py` to collect the necessary environmental information and paste it here.
> 2. You may add an addition that may be helpful for locating the problem, such as
>    
>    * How you installed PyTorch [e.g., pip, conda, source]
>    * Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
> 
> **Error traceback**
> 
> If applicable, paste the error trackback here.
> 
> ```
> A placeholder for trackback.
> ```
> 
> **Bug fix**
> 
> If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!



>

**Comment by 2458zhanghehe** [comment] 2023-03-06 05:18
@xiexinch 
the issue comes when i run the trian.py with my own dataset in the coco form
now i have successfully run the model with Voc form instead
i think it because i did not find the place where "instance_train.json" should fill or modify,i use the customdataset

**Comment by 2458zhanghehe** [comment] 2023-03-06 05:21
@xiexinch 
the issue comes when i run the trian.py with my own dataset in the coco form
now i have successfully run the model with Voc form instead
i think it because i did not find the place where "instance_train.json" should fill or modify,i use the customdataset

**Comment by 2458zhanghehe** [comment] 2023-03-06 05:26
@xiexinch 
by the way i use the autodl server instead of my own computer

when i test the model trained in VOC form with one image,another issue appear:
cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:983: error: (-2:Unspecified error) could not find encoder for the specified extension in function 'imencode'

but when i test the model with command:
python tools/test.py configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py \
    checkpoints/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth \
    --show-dir psp_r50_512x1024_40ki_cityscapes_results
it success also
do you now why

**Comment by 2458zhanghehe** [comment] 2023-03-06 05:37
@xiexinch 
img_path = "/root/autodl-tmp/mmsegmentation/data/1.png"
config_file = '/root/autodl-tmp/mmsegmentation/configs/aa//fcn_unet_s5-d16_256x256_40k_hrf.py'
checkpoint_file = '/root/autodl-tmp/mmsegmentation/aa_log/latest.pth'
model = init_segmentor(config_file,checkpoint_file)
result = inference_segmentor(model,img_path)

show_result_pyplot(model,img_path,result,out_file='tests')

**Comment by 2458zhanghehe** [comment] 2023-03-06 05:45
@xiexinch the test issue i have solved
reference:https://blog.csdn.net/shenhaibb_/article/details/128936390

**Closed** 2023-03-09 07:59 UTC
Labels: awaiting response
