### ISSUE TITLE
about loss

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#1225] opened 2022-01-22 10:07 UTC
It seems that official codes are built on crossentropyloss,and when i change to other loss ,it show me some errors?perhaps I'm using in a wrong way?
loss_decode=dict(type='DiceLoss',smooth=1,exponet=2,loss_weight=1.0)
Errors:
AttributeError:'tuple' object has no attribute 'get'
Thanks

**Comment by MengzhangLI** [comment] 2022-01-22 10:34
In my opinion, it is not caused by your listed code. 
![image](https://user-images.githubusercontent.com/24582831/150634985-8df4476f-5258-43e6-9cfa-2e245d093fe3.png)

You can follow unit test or our documents when you meet some debugs, in this issue, it may be found here:
https://github.com/open-mmlab/mmsegmentation/blob/master/tests/test_models/test_losses/test_dice_loss.py#L54-L65

**Comment by Lsz-20** [comment] 2022-01-22 10:50
> In my opinion, it is not caused by your listed code. ![image](https://user-images.githubusercontent.com/24582831/150634985-8df4476f-5258-43e6-9cfa-2e245d093fe3.png)
> 
> You can follow unit test or our documents when you meet some debugs, in this issue, it may be found here: https://github.com/open-mmlab/mmsegmentation/blob/master/tests/test_models/test_losses/test_dice_loss.py#L54-L65
Thanks for your advice,but it came up in the course of my training?and i follow the context but it seems the same question?

**Comment by MengzhangLI** [comment] 2022-01-22 11:19
Could you try to upload mmseg to latest version and try again? (check out MMCV version, either.)

**Comment by MengzhangLI** [comment] 2022-01-27 04:05
I would close it but feel free to contact us.

**Closed by MengzhangLI** 2022-01-27 04:05 UTC
